# Generated by Django 4.2.7 on 2023-11-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('insight', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=255)),
                ('start_year', models.CharField(max_length=255)),
                ('impact', models.CharField(max_length=255)),
                ('added', models.CharField(max_length=255)),
                ('published', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('relevance', models.CharField(max_length=255)),
                ('pestle', models.CharField(max_length=255)),
                ('source1', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('likelihood', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'my_data',
            },
        ),
    ]
