# Generated by Django 4.2.7 on 2023-11-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mydata',
            options={'managed': False},
        ),
    ]
