# Generated by Django 4.2.7 on 2023-11-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mydata_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
